# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'moodyTrainer.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(951, 601)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.494, y1:0, x2:0.431227, y2:1, stop:0 rgba(0, 161, 255, 255), stop:1 rgba(10, 85, 124, 255))\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.startBtn = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.startBtn.setFont(font)
        self.startBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.startBtn.setObjectName("startBtn")
        self.gridLayout_3.addWidget(self.startBtn, 2, 1, 2, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 1, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 0, 1, 1)
        self.titleLabel = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("background: transparent;\n"
"text-color: white;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout_3.addWidget(self.titleLabel, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 4, 2, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.imageLabel = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.imageLabel.setFont(font)
        self.imageLabel.setStyleSheet("background: transparent;")
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayout_4.addWidget(self.imageLabel, 4, 0, 1, 2)
        self.facePGRating = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.facePGRating.setFont(font)
        self.facePGRating.setStyleSheet("background: transparent;")
        self.facePGRating.setAlignment(QtCore.Qt.AlignCenter)
        self.facePGRating.setObjectName("facePGRating")
        self.gridLayout_4.addWidget(self.facePGRating, 5, 2, 1, 2)
        self.label = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: transparent;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 3, 0, 1, 4)
        self.resultsBtn = QtWidgets.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.resultsBtn.setFont(font)
        self.resultsBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.resultsBtn.setObjectName("resultsBtn")
        self.gridLayout_4.addWidget(self.resultsBtn, 7, 2, 1, 2)
        self.imagePrev = QtWidgets.QLabel(self.page_2)
        self.imagePrev.setStyleSheet("background: transparent;")
        self.imagePrev.setText("")
        self.imagePrev.setPixmap(QtGui.QPixmap("../Pictures/Saved Pictures/pika2.png"))
        self.imagePrev.setAlignment(QtCore.Qt.AlignCenter)
        self.imagePrev.setObjectName("imagePrev")
        self.gridLayout_4.addWidget(self.imagePrev, 5, 0, 1, 2)
        self.uploadBtn = QtWidgets.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.uploadBtn.setFont(font)
        self.uploadBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.uploadBtn.setObjectName("uploadBtn")
        self.gridLayout_4.addWidget(self.uploadBtn, 7, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background: transparent;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 4, 2, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 9, 0, 2, 2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 9, 2, 2, 2)
        self.exitBtn = QtWidgets.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.exitBtn.setFont(font)
        self.exitBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.exitBtn.setObjectName("exitBtn")
        self.gridLayout_4.addWidget(self.exitBtn, 11, 0, 1, 1)
        self.textPGTypeBtn = QtWidgets.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.textPGTypeBtn.setFont(font)
        self.textPGTypeBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.textPGTypeBtn.setObjectName("textPGTypeBtn")
        self.gridLayout_4.addWidget(self.textPGTypeBtn, 11, 1, 1, 1)
        self.textPGImageBtn = QtWidgets.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.textPGImageBtn.setFont(font)
        self.textPGImageBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"   border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.textPGImageBtn.setObjectName("textPGImageBtn")
        self.gridLayout_4.addWidget(self.textPGImageBtn, 11, 2, 1, 1)
        self.quizModeBtn = QtWidgets.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.quizModeBtn.setFont(font)
        self.quizModeBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.quizModeBtn.setObjectName("quizModeBtn")
        self.gridLayout_4.addWidget(self.quizModeBtn, 11, 3, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textPGImageBtn2 = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.textPGImageBtn2.setFont(font)
        self.textPGImageBtn2.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.textPGImageBtn2.setObjectName("textPGImageBtn2")
        self.gridLayout_5.addWidget(self.textPGImageBtn2, 9, 2, 1, 1)
        self.exitBtn2 = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.exitBtn2.setFont(font)
        self.exitBtn2.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.exitBtn2.setObjectName("exitBtn2")
        self.gridLayout_5.addWidget(self.exitBtn2, 9, 0, 1, 1)
        self.quizModeBtn2 = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.quizModeBtn2.setFont(font)
        self.quizModeBtn2.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.quizModeBtn2.setObjectName("quizModeBtn2")
        self.gridLayout_5.addWidget(self.quizModeBtn2, 9, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background: transparent;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 4)
        self.facePGBtn = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.facePGBtn.setFont(font)
        self.facePGBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.facePGBtn.setObjectName("facePGBtn")
        self.gridLayout_5.addWidget(self.facePGBtn, 9, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 6, 0, 1, 2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setStyleSheet("background: white;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_5.addWidget(self.plainTextEdit, 4, 0, 1, 2)
        self.textPGRating = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.textPGRating.setFont(font)
        self.textPGRating.setAlignment(QtCore.Qt.AlignCenter)
        self.textPGRating.setObjectName("textPGRating")
        self.gridLayout_5.addWidget(self.textPGRating, 4, 2, 1, 2)
        self.resultsBtn2 = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.resultsBtn2.setFont(font)
        self.resultsBtn2.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.resultsBtn2.setObjectName("resultsBtn2")
        self.gridLayout_5.addWidget(self.resultsBtn2, 6, 2, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 7, 0, 2, 2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 7, 2, 2, 2)
        self.textLabel = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.textLabel.setFont(font)
        self.textLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel.setObjectName("textLabel")
        self.gridLayout_5.addWidget(self.textLabel, 1, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 2, 1, 2)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background: transparent;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 4)
        self.textPGRating2 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.textPGRating2.setFont(font)
        self.textPGRating2.setAlignment(QtCore.Qt.AlignCenter)
        self.textPGRating2.setObjectName("textPGRating2")
        self.gridLayout_6.addWidget(self.textPGRating2, 2, 2, 1, 2)
        self.imagePrev2 = QtWidgets.QLabel(self.page_4)
        self.imagePrev2.setText("")
        self.imagePrev2.setPixmap(QtGui.QPixmap("../Pictures/Saved Pictures/pika2.png"))
        self.imagePrev2.setAlignment(QtCore.Qt.AlignCenter)
        self.imagePrev2.setObjectName("imagePrev2")
        self.gridLayout_6.addWidget(self.imagePrev2, 2, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 1, 2, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem10, 6, 0, 2, 2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem11, 6, 2, 2, 2)
        self.uploadBtn2 = QtWidgets.QPushButton(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.uploadBtn2.setFont(font)
        self.uploadBtn2.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.uploadBtn2.setObjectName("uploadBtn2")
        self.gridLayout_6.addWidget(self.uploadBtn2, 5, 0, 1, 2)
        self.resultsBtn3 = QtWidgets.QPushButton(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.resultsBtn3.setFont(font)
        self.resultsBtn3.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"   border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.resultsBtn3.setObjectName("resultsBtn3")
        self.gridLayout_6.addWidget(self.resultsBtn3, 5, 2, 1, 2)
        self.exitBtn3 = QtWidgets.QPushButton(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.exitBtn3.setFont(font)
        self.exitBtn3.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.exitBtn3.setObjectName("exitBtn3")
        self.gridLayout_6.addWidget(self.exitBtn3, 8, 0, 1, 1)
        self.textPGTypeBtn2 = QtWidgets.QPushButton(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.textPGTypeBtn2.setFont(font)
        self.textPGTypeBtn2.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.textPGTypeBtn2.setObjectName("textPGTypeBtn2")
        self.gridLayout_6.addWidget(self.textPGTypeBtn2, 8, 1, 1, 1)
        self.facePGBtn2 = QtWidgets.QPushButton(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.facePGBtn2.setFont(font)
        self.facePGBtn2.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.facePGBtn2.setObjectName("facePGBtn2")
        self.gridLayout_6.addWidget(self.facePGBtn2, 8, 2, 1, 1)
        self.quizModeBtn3 = QtWidgets.QPushButton(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.quizModeBtn3.setFont(font)
        self.quizModeBtn3.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.quizModeBtn3.setObjectName("quizModeBtn3")
        self.gridLayout_6.addWidget(self.quizModeBtn3, 8, 3, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.exitBtn4 = QtWidgets.QPushButton(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.exitBtn4.setFont(font)
        self.exitBtn4.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.exitBtn4.setObjectName("exitBtn4")
        self.gridLayout_7.addWidget(self.exitBtn4, 11, 0, 1, 1)
        self.angerBtn = QtWidgets.QPushButton(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.angerBtn.setFont(font)
        self.angerBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.angerBtn.setObjectName("angerBtn")
        self.gridLayout_7.addWidget(self.angerBtn, 5, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem12, 9, 0, 1, 4)
        self.label_9 = QtWidgets.QLabel(self.page_5)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../Pictures/Saved Pictures/pika2.png"))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 3, 0, 2, 2)
        self.label_8 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background: transparent;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 2, 0, 1, 4)
        self.textPGTypeBtn3 = QtWidgets.QPushButton(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.textPGTypeBtn3.setFont(font)
        self.textPGTypeBtn3.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.textPGTypeBtn3.setObjectName("textPGTypeBtn3")
        self.gridLayout_7.addWidget(self.textPGTypeBtn3, 11, 2, 1, 1)
        self.facePGBtn3 = QtWidgets.QPushButton(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.facePGBtn3.setFont(font)
        self.facePGBtn3.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.facePGBtn3.setObjectName("facePGBtn3")
        self.gridLayout_7.addWidget(self.facePGBtn3, 11, 3, 1, 1)
        self.disgustBtn = QtWidgets.QPushButton(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.disgustBtn.setFont(font)
        self.disgustBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"   border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.disgustBtn.setObjectName("disgustBtn")
        self.gridLayout_7.addWidget(self.disgustBtn, 7, 0, 1, 1)
        self.fearBtn = QtWidgets.QPushButton(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.fearBtn.setFont(font)
        self.fearBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.fearBtn.setObjectName("fearBtn")
        self.gridLayout_7.addWidget(self.fearBtn, 8, 0, 1, 1)
        self.neutralBtn = QtWidgets.QPushButton(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.neutralBtn.setFont(font)
        self.neutralBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"   border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.neutralBtn.setObjectName("neutralBtn")
        self.gridLayout_7.addWidget(self.neutralBtn, 8, 1, 1, 1)
        self.surprisedBtn = QtWidgets.QPushButton(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.surprisedBtn.setFont(font)
        self.surprisedBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.surprisedBtn.setObjectName("surprisedBtn")
        self.gridLayout_7.addWidget(self.surprisedBtn, 7, 1, 1, 1)
        self.sadBtn = QtWidgets.QPushButton(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.sadBtn.setFont(font)
        self.sadBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.sadBtn.setObjectName("sadBtn")
        self.gridLayout_7.addWidget(self.sadBtn, 6, 1, 1, 1)
        self.contemptBtn = QtWidgets.QPushButton(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.contemptBtn.setFont(font)
        self.contemptBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"   border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.contemptBtn.setObjectName("contemptBtn")
        self.gridLayout_7.addWidget(self.contemptBtn, 6, 0, 1, 1)
        self.textPGImageBtn3 = QtWidgets.QPushButton(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.textPGImageBtn3.setFont(font)
        self.textPGImageBtn3.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.textPGImageBtn3.setObjectName("textPGImageBtn3")
        self.gridLayout_7.addWidget(self.textPGImageBtn3, 11, 1, 1, 1)
        self.emotionOutputLabel = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.emotionOutputLabel.setFont(font)
        self.emotionOutputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.emotionOutputLabel.setObjectName("emotionOutputLabel")
        self.gridLayout_7.addWidget(self.emotionOutputLabel, 5, 2, 4, 2)
        self.happyBtn = QtWidgets.QPushButton(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.happyBtn.setFont(font)
        self.happyBtn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid White;\n"
"    border-radius: 7px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 white, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.happyBtn.setObjectName("happyBtn")
        self.gridLayout_7.addWidget(self.happyBtn, 5, 1, 1, 1)
        self.quizCheckLabel = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(30)
        self.quizCheckLabel.setFont(font)
        self.quizCheckLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.quizCheckLabel.setObjectName("quizCheckLabel")
        self.gridLayout_7.addWidget(self.quizCheckLabel, 3, 2, 2, 2)
        self.stackedWidget.addWidget(self.page_5)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Moody Trainer"))
        self.startBtn.setText(_translate("MainWindow", "Start"))
        self.titleLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Moody </span></p></body></html>"))
        self.imageLabel.setText(_translate("MainWindow", "Image Preview"))
        self.facePGRating.setText(_translate("MainWindow", "<Rating>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Face Playground</span></p></body></html>"))
        self.resultsBtn.setText(_translate("MainWindow", "Get Results"))
        self.uploadBtn.setText(_translate("MainWindow", "Upload Image"))
        self.label_3.setText(_translate("MainWindow", "Results"))
        self.exitBtn.setText(_translate("MainWindow", "Exit"))
        self.textPGTypeBtn.setText(_translate("MainWindow", "Text Playground (Typing)"))
        self.textPGImageBtn.setText(_translate("MainWindow", "Text Playground (Image)"))
        self.quizModeBtn.setText(_translate("MainWindow", "Quiz Mode (Faces)"))
        self.textPGImageBtn2.setText(_translate("MainWindow", "Text Playground (Image)"))
        self.exitBtn2.setText(_translate("MainWindow", "Exit"))
        self.quizModeBtn2.setText(_translate("MainWindow", "Quiz Mode (Faces)"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Text Playground</span></p></body></html>"))
        self.facePGBtn.setText(_translate("MainWindow", "Face Playground"))
        self.pushButton.setText(_translate("MainWindow", "Change to Image to text mode"))
        self.textPGRating.setText(_translate("MainWindow", "<Rating>"))
        self.resultsBtn2.setText(_translate("MainWindow", "Get Results"))
        self.textLabel.setText(_translate("MainWindow", "Type Your Sentence"))
        self.label_5.setText(_translate("MainWindow", "Results"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Text Playground</span></p></body></html>"))
        self.textPGRating2.setText(_translate("MainWindow", "<Results>"))
        self.label_2.setText(_translate("MainWindow", "Image Preview"))
        self.label_7.setText(_translate("MainWindow", "Results"))
        self.uploadBtn2.setText(_translate("MainWindow", "Upload Image of Text"))
        self.resultsBtn3.setText(_translate("MainWindow", "Get Results"))
        self.exitBtn3.setText(_translate("MainWindow", "Exit"))
        self.textPGTypeBtn2.setText(_translate("MainWindow", "Text Playground (Typing)"))
        self.facePGBtn2.setText(_translate("MainWindow", "Face Playground"))
        self.quizModeBtn3.setText(_translate("MainWindow", "Quiz Mode (Faces)"))
        self.exitBtn4.setText(_translate("MainWindow", "Exit"))
        self.angerBtn.setText(_translate("MainWindow", "Anger"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Face Quiz</span></p></body></html>"))
        self.textPGTypeBtn3.setText(_translate("MainWindow", "Text Playground (Typing)"))
        self.facePGBtn3.setText(_translate("MainWindow", "Face Playground"))
        self.disgustBtn.setText(_translate("MainWindow", "Disgust"))
        self.fearBtn.setText(_translate("MainWindow", "Fear"))
        self.neutralBtn.setText(_translate("MainWindow", "Neutral"))
        self.surprisedBtn.setText(_translate("MainWindow", "Surprised"))
        self.sadBtn.setText(_translate("MainWindow", "Sad"))
        self.contemptBtn.setText(_translate("MainWindow", "Contempt"))
        self.textPGImageBtn3.setText(_translate("MainWindow", "Text Playground (Image)"))
        self.emotionOutputLabel.setText(_translate("MainWindow", "<Actual Emotion>"))
        self.happyBtn.setText(_translate("MainWindow", "Happy"))
        self.quizCheckLabel.setText(_translate("MainWindow", "<Correct or Incorrect>"))

"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
"""